"""Video and coverpage added

Revision ID: 745307b71c04
Revises: 
Create Date: 2024-08-03 02:34:58.831135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745307b71c04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comment_replies', 'users', ['user_id'], ['user_id'])
    op.add_column('movies', sa.Column('video_data', sa.LargeBinary(), nullable=True))
    op.add_column('movies', sa.Column('coverimage_data', sa.LargeBinary(), nullable=True))
    op.create_foreign_key(None, 'parent_comments', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'parent_comments', 'movies', ['movie_id'], ['movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent_comments', type_='foreignkey')
    op.drop_constraint(None, 'parent_comments', type_='foreignkey')
    op.drop_column('movies', 'coverimage_data')
    op.drop_column('movies', 'video_data')
    op.drop_constraint(None, 'comment_replies', type_='foreignkey')
    # ### end Alembic commands ###
